// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZupDvLHbTtl9FU9vg6QuB_f0A4VBcuTk',
    appId: '1:323290004811:web:7449a4ff4830b1eb24fcce',
    messagingSenderId: '323290004811',
    projectId: 'fir-test-119',
    authDomain: 'fir-test-119.firebaseapp.com',
    storageBucket: 'fir-test-119.appspot.com',
    measurementId: 'G-N2DD4NNJ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRSBQq4huIvPGn7Rit7kymAZcNeEdgGgM',
    appId: '1:323290004811:android:b64d042120665ced24fcce',
    messagingSenderId: '323290004811',
    projectId: 'fir-test-119',
    storageBucket: 'fir-test-119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUydx3mn_3y8fHyThj6sxepigduZmiy_s',
    appId: '1:323290004811:ios:2a77971d62285b7e24fcce',
    messagingSenderId: '323290004811',
    projectId: 'fir-test-119',
    storageBucket: 'fir-test-119.appspot.com',
    iosClientId: '323290004811-1qvmm0i81029jo1t2cpkuhnlaj10tnbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest119',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUydx3mn_3y8fHyThj6sxepigduZmiy_s',
    appId: '1:323290004811:ios:2a77971d62285b7e24fcce',
    messagingSenderId: '323290004811',
    projectId: 'fir-test-119',
    storageBucket: 'fir-test-119.appspot.com',
    iosClientId: '323290004811-1qvmm0i81029jo1t2cpkuhnlaj10tnbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest119',
  );
}
